// app/press-statements/page.tsx
'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Calendar, FileText, ArrowLeft, Search } from 'lucide-react';
import Link from 'next/link';
import Header from '../components/layout/Header';
import Footer from '../components/layout/Footer';
import BackToTop from '../components/ui/BackToTop';

export default function PressStatementsPage() {
  const [searchTerm, setSearchTerm] = useState('');

  const statements = [
    {
      id: 1,
      title: 'بيان حول أزمة التعليم العالي',
      excerpt: 'بيان صحفي يتناول التحديات التي تواجه التعليم العالي والحلول المقترحة لتطوير المنظومة التعليمية وضمان جودة التعليم للجميع',
      date: '2024-01-20',
      category: 'تعليم',
      urgent: true,
      views: '15.2K',
      shares: '1.8K',
    },
    {
      id: 2,
      title: 'موقف من قضايا البيئة والتغير المناخي',
      excerpt: 'بيان يوضح الموقف الرسمي من قضايا البيئة والتغير المناخي والإجراءات المطلوبة للحفاظ على البيئة وتحقيق التنمية المستدامة',
      date: '2024-01-15',
      category: 'بيئة',
      urgent: false,
      views: '12.8K',
      shares: '2.1K',
    },
    {
      id: 3,
      title: 'تصريح حول الإصلاحات الاقتصادية',
      excerpt: 'تصريح صحفي حول الإصلاحات الاقتصادية المطلوبة وتأثيرها على الطبقات الشعبية والمتوسطة وسبل ضمان العدالة الاجتماعية',
      date: '2024-01-08',
      category: 'اقتصاد',
      urgent: false,
      views: '18.5K',
      shares: '3.2K',
    },
  ];

  const filteredStatements = statements.filter(statement => {
    const matchesSearch = statement.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         statement.excerpt.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesSearch;
  });

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-20">
        <div className="container mx-auto px-4 py-12">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-12"
          >
            <h1 className="text-4xl md:text-5xl font-bold text-brand-dark mb-6">
              البيانات الصحفية
            </h1>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              مجموعة شاملة من البيانات والتصريحات الصحفية حول القضايا المهمة والمواقف الرسمية
            </p>
          </motion.div>

          {/* Search */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="bg-white rounded-2xl p-6 shadow-lg mb-12"
          >
            <div className="relative max-w-md mx-auto">
              <Search className="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                placeholder="البحث في البيانات الصحفية..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pr-12 pl-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
              />
            </div>
          </motion.div>

          {/* Statements List */}
          <div className="space-y-8">
            {filteredStatements.map((statement, index) => (
              <motion.article
                key={statement.id}
                initial={{ opacity: 0, x: -30 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-100"
              >
                <div className="flex flex-col lg:flex-row lg:items-start lg:space-x-reverse lg:space-x-6">
                  <div className="flex-1">
                    <div className="flex items-center space-x-reverse space-x-4 mb-4">
                      <div className="w-12 h-12 bg-brand/10 rounded-full flex items-center justify-center">
                        <FileText className="w-6 h-6 text-brand" />
                      </div>
                      <div className="flex items-center space-x-reverse space-x-4">
                        <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                          statement.urgent 
                            ? 'bg-red-100 text-red-800' 
                            : 'bg-brand/10 text-brand'
                        }`}>
                          {statement.urgent ? 'عاجل' : statement.category}
                        </span>
                        <div className="flex items-center space-x-reverse space-x-2 text-sm text-gray-500">
                          <Calendar className="w-4 h-4" />
                          <span>{new Date(statement.date).toLocaleDateString('ar-EG')}</span>
                        </div>
                      </div>
                    </div>

                    <h2 className="text-2xl font-bold text-gray-800 mb-4 hover:text-brand transition-colors">
                      {statement.title}
                    </h2>
                    
                    <p className="text-gray-600 leading-relaxed mb-6">
                      {statement.excerpt}
                    </p>

                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-reverse space-x-6 text-sm text-gray-500 hide-press-stats">
                        <span>{statement.views} مشاهدة</span>
                        <span>{statement.shares} مشاركة</span>
                      </div>
                      
                      <Link
                        href={`/press-statements/${statement.id}`}
                        className="flex items-center space-x-reverse space-x-2 text-brand font-medium hover:text-brand-dark transition-colors group"
                      >
                        <span>قراءة البيان كاملاً</span>
                        <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
                      </Link>
                    </div>
                  </div>
                </div>
              </motion.article>
            ))}
          </div>

          {/* No Results */}
          {filteredStatements.length === 0 && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-12"
            >
              <p className="text-xl text-gray-500">لا توجد بيانات تطابق البحث</p>
            </motion.div>
          )}
        </div>
      </main>
      <Footer />
      <BackToTop />
    </div>
  );
}

// pages/press-statements/index.vue
<template>
  <div class="min-h-screen bg-background pt-20">
    <div class="container mx-auto px-4 py-12">
      <!-- Header -->
      <div class="text-center mb-12">
        <h1 class="text-4xl md:text-5xl font-bold text-brand-dark mb-6">
          البيانات الصحفية
        </h1>
        <p class="text-xl text-gray-600 max-w-3xl mx-auto">
          جميع البيانات والتصريحات الصحفية حول القضايا المهمة
        </p>
        <p v-if="totalItems > 0" class="text-sm text-gray-500 mt-4">
          عرض {{ statements.length }} من أصل {{ totalItems }} بيان
        </p>
      </div>

      <!-- Search -->
      <div class="bg-white rounded-2xl p-6 shadow-lg mb-12">
        <div class="relative w-full">
          <Icon
            name="lucide:search"
            class="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5"
          />
          <input
            v-model="searchTerm"
            type="text"
            placeholder="البحث في البيانات الصحفية..."
            class="w-full pr-12 pl-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
            @input="debouncedSearch"
          />
        </div>
      </div>

      <!-- Loading -->
      <div v-if="pending" class="flex justify-center items-center py-12">
        <div
          class="animate-spin rounded-full h-12 w-12 border-b-2 border-brand"
        ></div>
        <span class="mr-3 text-gray-600">جاري تحميل البيانات...</span>
      </div>

      <!-- Error -->
      <div v-else-if="error" class="text-center py-12">
        <div
          class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4"
        >
          <Icon name="lucide:alert-circle" class="w-8 h-8 text-red-500" />
        </div>
        <h3 class="text-lg font-semibold text-gray-800 mb-2">عذراً، حدث خطأ</h3>
        <p class="text-gray-600 mb-6">
          {{ error.message || "حدث خطأ في تحميل البيانات" }}
        </p>
        <button
          @click="refresh()"
          class="bg-brand text-white px-6 py-3 rounded-lg hover:bg-brand-dark transition-colors"
        >
          إعادة المحاولة
        </button>
      </div>

      <!-- Press Statements Grid -->
      <div v-else-if="statements.length > 0">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          <article
            v-for="statement in statements"
            :key="statement.id"
            class="bg-white rounded-2xl p-6 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2"
          >
            <div class="flex items-center justify-between mb-4">
              <span
                class="px-3 py-1 rounded-full text-sm font-medium bg-blue-100 text-blue-800"
              >
                {{ statement.category.name }}
              </span>
              <div
                class="flex items-center space-x-reverse space-x-2 text-gray-500 text-sm"
              >
                <Icon name="lucide:calendar" class="w-4 h-4" />
                <span>{{ formatDate(statement.date) }}</span>
              </div>
            </div>

            <h3 class="text-xl font-bold text-brand-dark mb-4">
              {{ statement.title }}
            </h3>

            <p class="text-gray-600 mb-6">
              {{ statement.excerpt }}
            </p>

            <NuxtLink
              :to="`/press-statements/${statement.id}`"
              class="w-full bg-brand text-white py-3 rounded-lg font-semibold hover:bg-brand-dark transition-colors block text-center"
            >
              اقرأ البيان كاملاً
            </NuxtLink>
          </article>
        </div>

        <!-- Pagination -->
        <ArticlesPagination
          v-if="totalPages > 1"
          :current-page="currentPage"
          :total-pages="totalPages"
          :has-prev="hasPrev"
          :has-next="hasNext"
          @page-change="handlePageChange"
        />
      </div>

      <!-- No Results -->
      <div v-else class="text-center py-12">
        <div
          class="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6"
        >
          <Icon name="lucide:search" class="w-12 h-12 text-gray-400" />
        </div>
        <h3 class="text-2xl font-bold text-gray-800 mb-4">
          لا توجد بيانات صحفية
        </h3>
        <p class="text-xl text-gray-500 mb-8">
          {{
            searchTerm
              ? "لا توجد بيانات تطابق البحث"
              : "لم يتم العثور على أي بيانات صحفية"
          }}
        </p>
        <button
          v-if="searchTerm"
          @click="clearSearch"
          class="bg-brand text-white px-6 py-3 rounded-lg hover:bg-brand-dark transition-colors"
        >
          مسح البحث
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useDebounceFn } from "@vueuse/core";

const route = useRoute();
const router = useRouter();
const { $api } = useNuxtApp();

// Reactive state
const searchTerm = ref("");
const currentPage = ref(parseInt(route.query.page) || 1);

// Computed query params for API call
const queryParams = computed(() => {
  const params = {
    page: currentPage.value,
    limit: 12,
  };
  
  if (searchTerm.value) {
    params.search = searchTerm.value;
  }
  
  return params;
});

// Use useAPI directly in setup
const { data: apiResponse, pending, error, refresh } = await useAPI(
  "/press-statements",
  {
    query: queryParams,
    watch: [queryParams]
  }
);

// Computed properties from API response
const statements = computed(() => apiResponse.value?.data || []);
const totalItems = computed(() => apiResponse.value?.total || 0);
const totalPages = computed(() => Math.ceil((apiResponse.value?.total || 0) / 12));
const hasNext = computed(() => currentPage.value < totalPages.value);
const hasPrev = computed(() => currentPage.value > 1);

// Function to manually fetch using $api when needed
const fetchStatements = async () => {
  try {
    const params = {
      page: currentPage.value,
      limit: 12,
    };

    if (searchTerm.value) {
      params.search = searchTerm.value;
    }

    const response = await $api("/press-statements", {
      query: params,
    });

    return response;
  } catch (err) {
    console.error("Error fetching press statements:", err);
    throw err;
  }
};

// Methods
const handlePageChange = (page) => {
  currentPage.value = page;
  const query = { ...route.query, page };
  if (searchTerm.value) {
    query.search = searchTerm.value;
  }
  router.push({ query });
  if (import.meta.client) {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
};

const clearSearch = () => {
  searchTerm.value = "";
  currentPage.value = 1;
  router.push({ query: {} });
};

// Debounced search
const debouncedSearch = useDebounceFn(() => {
  currentPage.value = 1;
  const query = { page: 1 };
  if (searchTerm.value) {
    query.search = searchTerm.value;
  }
  router.push({ query });
}, 300);

// Watch for route changes
watch(
  () => route.query.page,
  (newPage) => {
    currentPage.value = parseInt(newPage) || 1;
  }
);

// Watch for search term in URL
watch(
  () => route.query.search,
  (newSearch) => {
    searchTerm.value = newSearch || "";
  }
);

// Initialize search term from URL
searchTerm.value = route.query.search || "";

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString("ar-EG");
};

// SEO
useHead({
  title: "البيانات الصحفية - محمد عبدالعليم داود",
  meta: [
    {
      name: "description",
      content: "جميع البيانات والتصريحات الصحفية حول القضايا المهمة",
    },
  ],
});
</script>
