// pages/press-statements.vue
<template>
  <div class="min-h-screen bg-background pt-20">
    <div class="container mx-auto px-4 py-12">
      <!-- Header -->
      <div class="text-center mb-16">
        <h1 class="text-4xl md:text-5xl font-bold text-brand-dark mb-6">
          البيانات الصحفية
        </h1>
        <p class="text-xl text-gray-600 max-w-3xl mx-auto">
          جميع البيانات والتصريحات الصحفية حول القضايا المهمة
        </p>
      </div>

      <!-- Press Statements Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <article
          v-for="(statement, index) in statements"
          :key="statement.id"
          class="bg-white rounded-2xl p-6 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2"
        >
          <div class="flex items-center justify-between mb-4">
            <span :class="[
              'px-3 py-1 rounded-full text-sm font-medium',
              statement.priority === 'عاجل' ? 'bg-red-100 text-red-800' :
              statement.priority === 'مهم' ? 'bg-orange-100 text-orange-800' :
              'bg-blue-100 text-blue-800'
            ]">
              {{ statement.priority }}
            </span>
            <div class="flex items-center space-x-reverse space-x-2 text-gray-500 text-sm">
              <Icon name="lucide:calendar" class="w-4 h-4" />
              <span>{{ formatDate(statement.date) }}</span>
            </div>
          </div>

          <h3 class="text-xl font-bold text-brand-dark mb-4">
            {{ statement.title }}
          </h3>

          <p class="text-gray-600 mb-6">
            {{ statement.excerpt }}
          </p>

          <button class="w-full bg-brand text-white py-3 rounded-lg font-semibold hover:bg-brand-dark transition-colors">
            اقرأ البيان كاملاً
          </button>
        </article>
      </div>
    </div>
  </div>
</template>

<script setup>
const statements = ref([
  {
    id: 1,
    title: 'بيان حول قانون الإعلام الجديد',
    excerpt: 'نؤكد على أهمية تطوير قانون الإعلام بما يواكب التطورات التكنولوجية ويحافظ على حرية التعبير والرأي',
    date: '2024-01-20',
    priority: 'عاجل'
  },
  {
    id: 2,
    title: 'تصريح حول الأوضاع الاقتصادية',
    excerpt: 'نتابع بعناية التطورات الاقتصادية ونعمل على تقديم الحلول المناسبة لدعم المواطنين',
    date: '2024-01-18',
    priority: 'مهم'
  },
  {
    id: 3,
    title: 'بيان حول التعليم الرقمي',
    excerpt: 'ندعو إلى تطوير منظومة التعليم الرقمي وتوفير الأدوات اللازمة للطلاب والمعلمين',
    date: '2024-01-15',
    priority: 'عادي'
  }
])

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('ar-EG')
}

useHead({
  title: 'البيانات الصحفية - محمد عبدالعليم داود',
  meta: [
    { name: 'description', content: 'جميع البيانات والتصريحات الصحفية حول القضايا المهمة' }
  ]
})
</script>

// src/components/sections/PressStatements.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { Calendar, FileText, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { usePressStatements } from '../../hooks/useApi';
import LoadingSpinner from '../ui/LoadingSpinner';
import ErrorMessage from '../ui/ErrorMessage';

const PressStatements = () => {
  const { data: statements, loading, error, refetch } = usePressStatements();

  if (loading) {
    return (
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4">
          <LoadingSpinner text="جاري تحميل البيانات الصحفية..." />
        </div>
      </section>
    );
  }

  if (error) {
    return (
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4">
          <ErrorMessage message={error} onRetry={refetch} />
        </div>
      </section>
    );
  }

  return (
    <section className="py-20 bg-background">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold text-brand-dark mb-6">
            البيانات الصحفية
          </h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            أحدث البيانات والتصريحات الصحفية حول القضايا المهمة والمواقف الرسمية
          </p>
        </motion.div>

        <div className="max-w-4xl mx-auto space-y-8">
          {(statements || []).map((statement, index) => (
            <motion.div
              key={statement.id}
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-100"
            >
              <div className="flex flex-col lg:flex-row lg:items-start lg:space-x-reverse lg:space-x-6">
                <div className="flex-1">
                  <div className="flex items-center space-x-reverse space-x-4 mb-4">
                    <div className="w-12 h-12 bg-brand/10 rounded-full flex items-center justify-center">
                      <FileText className="w-6 h-6 text-brand" />
                    </div>
                    <div className="flex items-center space-x-reverse space-x-4">
                      <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                        statement.urgent 
                          ? 'bg-red-100 text-red-800' 
                          : 'bg-brand/10 text-brand'
                      }`}>
                        {statement.urgent ? 'عاجل' : statement.category}
                      </span>
                      <div className="flex items-center space-x-reverse space-x-2 text-sm text-gray-500">
                        <Calendar className="w-4 h-4" />
                        <span>{new Date(statement.date).toLocaleDateString('ar-EG')}</span>
                      </div>
                    </div>
                  </div>

                  <h3 className="text-2xl font-bold text-gray-800 mb-4 hover:text-brand transition-colors">
                    {statement.title}
                  </h3>
                  
                  <p className="text-gray-600 leading-relaxed mb-6">
                    {statement.excerpt}
                  </p>

                  <Link
                    to={`/press-statement/${statement.id}`}
                    className="flex items-center space-x-reverse space-x-2 text-brand font-medium hover:text-brand-dark transition-colors group"
                  >
                    <span>قراءة البيان كاملاً</span>
                    <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
                  </Link>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mt-12"
        >
          <Link
            to="/press-statements"
            className="bg-brand text-white px-8 py-4 rounded-full font-bold hover:bg-brand-dark transition-all duration-300 transform hover:scale-105 shadow-lg inline-block"
          >
            عرض جميع البيانات
          </Link>
        </motion.div>
      </div>
    </section>
  );
};

export default PressStatements;
