// app/pages/articles/index.vue
<template>
  <div class="min-h-screen bg-background pt-20">
    <div class="container mx-auto px-4 py-12">
      <!-- Header -->
      <div class="text-center mb-12">
        <h1 class="text-4xl md:text-5xl font-bold text-brand-dark mb-6">
          جميع المقالات
        </h1>
        <p class="text-xl text-gray-600 max-w-2xl mx-auto">
          مجموعة شاملة من المقالات والتحليلات في مختلف القضايا السياسية
          والاجتماعية
        </p>
        <p v-if="totalItems > 0" class="text-sm text-gray-500 mt-4">
          عرض {{ articles.length }} من أصل {{ totalItems }} مقال
        </p>
      </div>

      <!-- Search -->
      <div class="bg-white rounded-2xl p-6 shadow-lg mb-12">
        <div class="relative w-full">
          <Icon
            name="lucide:search"
            class="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5"
          />
          <input
            v-model="searchTerm"
            type="text"
            placeholder="البحث في المقالات..."
            class="w-full pr-12 pl-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
            @input="debouncedSearch"
          />
        </div>
      </div>

      <!-- Loading -->
      <div v-if="pending" class="flex justify-center items-center py-12">
        <div
          class="animate-spin rounded-full h-12 w-12 border-b-2 border-brand"
        ></div>
        <span class="mr-3 text-gray-600">جاري تحميل المقالات...</span>
      </div>

      <!-- Error -->
      <div v-else-if="error" class="text-center py-12">
        <div
          class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4"
        >
          <Icon name="lucide:alert-circle" class="w-8 h-8 text-red-500" />
        </div>
        <h3 class="text-lg font-semibold text-gray-800 mb-2">عذراً، حدث خطأ</h3>
        <p class="text-gray-600 mb-6">
          {{ error.message || "حدث خطأ في تحميل البيانات" }}
        </p>
        <button
          @click="refresh()"
          class="bg-brand text-white px-6 py-3 rounded-lg hover:bg-brand-dark transition-colors"
        >
          إعادة المحاولة
        </button>
      </div>

      <!-- Articles Grid -->
      <div v-else-if="articles.length > 0">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          <ArticleCard
            v-for="(article, index) in articles"
            :key="article.id"
            :article="article"
            :index="index"
          />
        </div>

        <!-- Pagination -->
        <ArticlesPagination
          v-if="totalPages > 1"
          :current-page="currentPage"
          :total-pages="totalPages"
          :has-prev="hasPrev"
          :has-next="hasNext"
          @page-change="handlePageChange"
        />
      </div>

      <!-- No Results -->
      <div v-else class="text-center py-12">
        <div
          class="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6"
        >
          <Icon name="lucide:search" class="w-12 h-12 text-gray-400" />
        </div>
        <h3 class="text-2xl font-bold text-gray-800 mb-4">لا توجد مقالات</h3>
        <p class="text-xl text-gray-500 mb-8">
          {{
            searchTerm
              ? "لا توجد مقالات تطابق البحث"
              : "لم يتم العثور على أي مقالات"
          }}
        </p>
        <button
          v-if="searchTerm"
          @click="clearSearch"
          class="bg-brand text-white px-6 py-3 rounded-lg hover:bg-brand-dark transition-colors"
        >
          مسح البحث
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useDebounceFn } from "@vueuse/core";

const route = useRoute();
const router = useRouter();
const { $api } = useNuxtApp();

// Reactive state
const searchTerm = ref("");
const currentPage = ref(parseInt(route.query.page) || 1);

// Computed query params for API call
const queryParams = computed(() => {
  const params = {
    page: currentPage.value,
    limit: 12,
  };

  if (searchTerm.value) {
    params.search = searchTerm.value;
  }

  return params;
});

// Use useAPI directly in setup
const {
  data: apiResponse,
  pending,
  error,
  refresh,
} = await useAPI("/articles", {
  query: queryParams,
  watch: [queryParams],
});

// Computed properties from API response
const articles = computed(() => apiResponse.value?.data || []);
const totalItems = computed(() => apiResponse.value?.total || 0);
const totalPages = computed(() =>
  Math.ceil((apiResponse.value?.total || 0) / 12)
);
const hasNext = computed(() => currentPage.value < totalPages.value);
const hasPrev = computed(() => currentPage.value > 1);

// Methods
const handlePageChange = (page) => {
  currentPage.value = page;
  const query = { ...route.query, page };
  if (searchTerm.value) {
    query.search = searchTerm.value;
  }
  router.push({ query });
  if (import.meta.client) {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
};

const clearSearch = () => {
  searchTerm.value = "";
  currentPage.value = 1;
  router.push({ query: {} });
};

// Debounced search
const debouncedSearch = useDebounceFn(() => {
  currentPage.value = 1;
  const query = { page: 1 };
  if (searchTerm.value) {
    query.search = searchTerm.value;
  }
  router.push({ query });
}, 300);

// Watch for route changes
watch(
  () => route.query.page,
  (newPage) => {
    currentPage.value = parseInt(newPage) || 1;
  }
);

// Watch for search term in URL
watch(
  () => route.query.search,
  (newSearch) => {
    searchTerm.value = newSearch || "";
  }
);

// Initialize data on mount
onMounted(() => {
  // Set search term from URL if present
  searchTerm.value = route.query.search || "";
});

// SEO
useHead({
  title: "جميع المقالات - محمد عبدالعليم داود",
  meta: [
    {
      name: "description",
      content:
        "مجموعة شاملة من المقالات والتحليلات في مختلف القضايا السياسية والاجتماعية",
    },
  ],
});
</script>

// app/articles/page.tsx
'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Calendar, Eye, Search, Filter, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import Header from '../components/layout/Header';
import Footer from '../components/layout/Footer';
import BackToTop from '../components/ui/BackToTop';
import articlesData from '../data/articles.json';

export default function AllArticlesPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('الكل');

  const categories = ['الكل', 'سياسة', 'اقتصاد', 'إعلام', 'حقوق إنسان', 'تعليم', 'صحة'];

  const filteredArticles = articlesData.filter(article => {
    const matchesSearch = article.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         article.excerpt.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = selectedCategory === 'الكل' || article.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-20">
        <div className="container mx-auto px-4 py-12">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-12"
          >
            <h1 className="text-4xl md:text-5xl font-bold text-brand-dark mb-6">
              جميع المقالات
            </h1>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              مجموعة شاملة من المقالات والتحليلات في مختلف القضايا السياسية والاجتماعية
            </p>
          </motion.div>

          {/* Search and Filter */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="bg-white rounded-2xl p-6 shadow-lg mb-12"
          >
            <div className="flex flex-col lg:flex-row gap-6">
              {/* Search */}
              <div className="flex-1 relative">
                <Search className="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                <input
                  type="text"
                  placeholder="البحث في المقالات..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pr-12 pl-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                />
              </div>

              {/* Categories */}
              <div className="flex items-center space-x-reverse space-x-2">
                <Filter className="text-gray-400 w-5 h-5" />
                <select
                  value={selectedCategory}
                  onChange={(e) => setSelectedCategory(e.target.value)}
                  className="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                >
                  {categories.map(category => (
                    <option key={category} value={category}>{category}</option>
                  ))}
                </select>
              </div>
            </div>
          </motion.div>

          {/* Articles Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {filteredArticles.map((article, index) => (
              <motion.div
                key={article.id}
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="bg-white rounded-2xl overflow-hidden shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2"
              >
                <div className="relative overflow-hidden">
                  <img
                    src={article.image}
                    alt={article.title}
                    className="w-full h-48 object-cover transition-transform duration-300 hover:scale-110"
                  />
                  <div className="absolute top-4 right-4">
                    <span className="bg-brand text-white px-3 py-1 rounded-full text-sm font-medium">
                      {article.category}
                    </span>
                  </div>
                </div>
                
                <div className="p-6">
                  <h3 className="text-xl font-bold text-gray-800 mb-3 line-clamp-2 hover:text-brand transition-colors">
                    {article.title}
                  </h3>
                  <p className="text-gray-600 mb-4 line-clamp-3 leading-relaxed">
                    {article.excerpt}
                  </p>
                  
                  <div className="flex items-center justify-between text-sm text-gray-500 mb-4">
                    <div className="flex items-center space-x-reverse space-x-2">
                      <Calendar className="w-4 h-4" />
                      <span>{new Date(article.date).toLocaleDateString('ar-EG')}</span>
                    </div>
                    <div className="flex items-center space-x-reverse space-x-4">
                      <div className="flex items-center space-x-reverse space-x-1">
                        <Eye className="w-4 h-4" />
                        <span>{article.views}</span>
                      </div>
                      <span>{article.readTime}</span>
                    </div>
                  </div>
                  
                  <Link
                    href={`/articles/${article.id}`}
                    className="flex items-center space-x-reverse space-x-2 text-brand font-medium hover:text-brand-dark transition-colors group"
                  >
                    <span>اقرأ المزيد</span>
                    <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
                  </Link>
                </div>
              </motion.div>
            ))}
          </div>

          {/* No Results */}
          {filteredArticles.length === 0 && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-12"
            >
              <p className="text-xl text-gray-500">لا توجد مقالات تطابق البحث</p>
            </motion.div>
          )}
        </div>
      </main>
      <Footer />
      <BackToTop />
    </div>
  );
}
